language: java

java:
  - oraclejdk8
  - openjdk8
  - oraclejdk9
  - openjdk9

cache:
  directories:
    - $HOME/.m2/repository

matrix:
  fast_finish: true
  include:
  - java: oraclejdk8
  - java: openjdk8
  allow_failures:
  - java: oraclejdk9
  - java: openjdk9
